### ISSUE TITLE
IntegrationTests.AspNetTests.SubmitMetrics [FAIL] System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:56433

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1004]
This one is the most frequently failing flaky test

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/7546662258?check_suite_focus=true

**Comment by pjanotti** [comment]
I couldn't repro this locally - which is not very surprising since we typically have more cpu and memory than the GH action instances. However, I also didn't find this error recently in the last CI job failures (notice that the job search is limited so my search was "manual"). In light of that let's close this issue and re-open if needed.
