### ISSUE TITLE
Remove StackExchange.Redis library from auto-instrumentation package

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1150]
# Bug Report

## Symptom

**Describe the bug**
`StackExchange.Redis.dll` library is present in the `tracer-home` folder. 

**Expected behavior**
We should remove this library from our package and utilize the reference from customer app.

There are other libraries like `MySql.Data.dll`, `Pipelines.Sockets.Unofficial.dll` which needs to be removed. If we plan to use it we may need to review the license information for these project.

**Comment by Kielek** [comment]
@pellared, IMO it is a blocker for 0.3.1 release discussed last SIG.
It is regression introduced by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1133/files#diff-3ccfa8e6e67b8d2d064e1e3d268128986aaa4cec4312bb0960b64f77317d7345

Potential root cause - dotnet ignores exclude assets https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/2c5b27709ac91f0610194029d0fe74c84325dd74/src/OpenTelemetry.AutoInstrumentation/OpenTelemetry.AutoInstrumentation.csproj#L34-L35
in transitive dependency https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/2c5b27709ac91f0610194029d0fe74c84325dd74/src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj#L17

Potential fix:
Extract Excluding assets to separate props file and include it both in `OpenTelemetry.AutoInstrumentation/OpenTelemetry.AutoInstrumentation.csproj` and `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj`.
It will be great to add tests to detect if the final folder does not contain any unneeded assemblies.
