### ISSUE TITLE
Extendibility via plugins

### ISSUE THREAD

**Issue by RassK** [open-telemetry/opentelemetry-dotnet-instrumentation#117]
### **Why**

Distro providers should have more simpler ways to build up their own distro. Full fork is hard to manage and keep in sync.

### **What**
Introduce plugin architecture for extendibility. Plugins could reside in `/plugins ` folder where `dll`s can be dynamically loaded. 

This feature is connected to: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/118

**Comment by pellared** [comment]
We need to agree on what extension points are needed.

For Splunk, we need to be able to add additional (or modify existing) HTTP response headers for HTTP Inbound instrumentation.

Maybe we should start with this one?

**Comment by pellared** [comment]
Instead of

> Plugins could reside in /plugins folder where dlls can be dynamically loaded.

I would prefer to add some env var like `OTEL_DOTNET_INSTR_PLUGIN`. Requiring to explicitly set it is more secure. It also gives the user to use different plugins for different application. It also makes it possible to harden the location where the plugin resides (e.g. aggressively restrict access to it as potential place where a malicious user could inject some sniffer).

**Comment by pellared** [comment]
For reference: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/566
