### ISSUE TITLE
GraphQL instrumentation: Update HTTP server span if it exists

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1322]
We may want to have a follow-up issue to control with type of activity we start here. In the case of aspnetcore hosting graphql, we will end up with 2 server spans, which may be confusing. We may want to use a setting to control whether this code updates the current server span or creates a new one if it doesn't exist, or to allow 2 separate (one from aspnetcore and the other internal span from graphql).

_Originally posted by @nrcventura in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1321#discussion_r985007331_

**Comment by pjanotti** [comment]
It makes sense to suppress downstream instrumentation in a few cases like done by grpc client instrumentation, see [here](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-1.3.0/src/OpenTelemetry.Instrumentation.GrpcNetClient#suppressdownstreaminstrumentation).

Instrumenting a client library like grpc that use other instrumented libraries for the actual RPC makes sense: it works nicely because the scope is limited by the logical execution context, i.e.: the suppression of other instrumentation only happens under the span being created for the grpc client request. So the scope is limited and it actually doesn't know what other instrumentations may be "under" it. An application that have grpc and HttpClient calls can use the flag because any HttpClient calls not under grpc client will still produce spans.

For server instrumentation we can't just suppress all instrumentations under the top span: it is very likely that one would miss instrumentations for other RPC calls (DB, queues, etc). It seems that if there is redundancy like in the GraphQL case we have a few options:

1. Use the enable/disable instrumentation to control the redundancy - limited because one may prefer the GraphQL spans but needs the AspNetCore ones for other requests that don't use GraphQL on the same server (is it possible?).
2. Control this from the GraphQL instrumentation directly by having a config option and checking during execution for the parent span.

Option 2 is doable but I don't think we would be able to do it consistently for many instrumentations that we don't own. In light of that I propose that we close/postpone this issue until we are sure that we really want to implement option 2.

cc @nrcventura

**Comment by pjanotti** [comment]
Independent of the comment above we should offer the possibility of enabling suppression for spans under grpc client.

**Comment by pjanotti** [comment]
SIG meeting:

- Change name of span? Is it allowed by SDK and Activity? It is allowed by the spec.
- Look for grpc core implementation handling of the "grpc span".

**Comment by pjanotti** [comment]
The grpc in deeply integrated into AspNetCore. The information that the request is actually a grpc request comes from AspNetCore itself, see [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0#grpc-service-tracing).

The instrumentation code leverages that to update the span to better describe the grpc request:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/e826f9d2337978cdcd6d5f623216c40d17e5b649/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L238

https://github.com/open-telemetry/opentelemetry-dotnet/blob/e826f9d2337978cdcd6d5f623216c40d17e5b649/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L399

**Comment by pjanotti** [comment]
@nrcventura @Kielek @pellared does everyone agree to close this one and do the work via #1396? i.e.: instead of trying to combine spans from different instrumentations we solve the issue by choosing the span kind of GraphQL according to the presence of a local parent.

**Comment by pellared** [comment]
I agree

**Comment by nrcventura** [comment]
Closing per SIG discussion. We will have 2 spans instead of combining them.
