### ISSUE TITLE
Document libraries in the store

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1380]
Might need to start documenting possible conflicting dependencies.

I see it brings 3 new dependencies >
* mongodb.libmongocrypt
* sharpcompress
* dnsclient

More worried about the last 2.

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1320#discussion_r990018319_

**Comment by Kielek** [comment]
Check with #1382

**Comment by RassK** [comment]
After a long investigation, seems there is no point to document these concrete dependencies. 
These are dependencies of `mongodb.driver.core`  that are also brought by an application that's using MongoDB.
Therefore we should not also ship `dnsclient` and `sharpcompress` and 'mongodb.driver.core' with .net shared store.
I think #1382 should be reopened, there are still a lot of things to remove.

Also I think this doc should be generated automatically somehow. The only important dependencies to write down extra are the ones potentially crashing the application (tests are anyway tracking the whole output).

**Comment by Kielek** [comment]
I agree that we should sheep only [MongoDB.Driver.Core.Extensions.DiagnosticSources](https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources) but on other indirect dependencies. Do you see any other similar issues? Or maybe the way how to automatically detect them?

Automatically generated documentation could be done in scope of this issue.

**Comment by RassK** [comment]
I guess (or hope) that even `MongoDB.Driver.Core.Extensions.DiagnosticSources` is not that important, since currently we say that we can work with customer's brought version or if it's not there, we will inject the version we brought.

To do it automatically we have to take apart packages we support, `OpenTelemetry.AutoInstrumentation`, `OpenTelemetry.AutoInstrumentation.AdditionalDeps`. This part is easy, we already have the resolver tool `DependencyListGenerator` (one analyser must be modified slightly).
1. packages we support - there might be no hard reference to the main project (like MongoDB is done). So this is pretty much manually defined list.
2. `OpenTelemetry.AutoInstrumentation` and `OpenTelemetry.AutoInstrumentation.AdditionalDeps` can just feed in the `csproj` to the modified `DependencyListGenerator` and get the whole deps list back.

The hardest part is to understand how .NET is choosing to upgrade versions, when multiple transient dlls have similar childs. If this is resolved, we can auto list all conflicting libs to the doc.

According to my manual tests, the biggest issue is `Microsoft.Extensions.Logging.Abstractions`, this one I had to reference for my test app. `System.Diagnostic.DiagnosticSource` will be auto upgraded (by additional deps) if there is no reference, so it's more like 50/50 case.

**Comment by pjanotti** [comment]
> I think https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1382 should be reopened, there are still a lot of things to remove.

I think this is important to be done soon. That said the current scale of the issue allows us to postpone fully automating the solution. I also want to think about how this can impact the NuGet work that we are starting.

**Comment by RassK** [comment]
Probably need to wait for https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1213, it's output is important.

I'm thinking to take TestApplications as a base to analyse supported instrumentations output (dlls) but this means TestApplications must be strictly using nothing extra. So far seems, these follow the rule.
