### ISSUE TITLE
Drop support for Jaeger Exporter

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1711]
As we are in pre 1.0.0 release, it will be good to remove it.
If someone needs it, there is a possibility to load it by plugin.

See https://github.com/open-telemetry/opentelemetry-specification/issues/2859

**Comment by pellared** [comment]
1. Jaeger is still very popular
2. Plugins should be used "as last resort", their primary use case is to allow creating distributions. I think that the users shouldn't not use them unless necessary.
3. Let's track the issue in the spec. For sure we should make a decision before 1.0.0.

**Comment by RassK** [comment]
Doesn't seem as a fat dependency in SDK. Since we also load it if we need it, there is not many issues keeping it until deprecation notice is official.

> Plugins should be used "as last resort", their primary use case is to allow creating distributions. I think that the users shouldn't not use them unless necessary.

Especially true without integration layer. Having integration through magic methods could cause loads of issues. At least distributors know more what's going on.

**Comment by pellared** [comment]
Deprecation note is official https://github.com/open-telemetry/opentelemetry-specification/pull/2858

I think we are good to remove it. Removing the "milestone" to discuss if we want to make it sooner.
