### ISSUE TITLE
Do not require .NET 6 SDK

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1723]
We should not require  .NET 6 SDK

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1720#discussion_r1042279428_

It should be easy to test on GitHub Codespaces.
Right now, without .NET 6 SDK, some tests are failing when `./build.sh Workflow` is executed.

**Comment by Kielek** [comment]
I have checked this.
Technically we could drop .NET 6 SDK requirements but instead of this we have to install .NET runtime 6.0 for dotnet and aspnetcore.
Without this tests are failing - there is no possibility to execute tests applications.

What is more .NET 6 SDK is installed on all used [runner-images](https://github.com/actions/runner-images). It is easier to do the same for alpine docker image and local env. than have specific requirements for this..

BTW I do not found any way to install only runtime through dotnet-install action.

Closing.
