### ISSUE TITLE
Refactor ConfigurationSources

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1728]
It could be enough to implement it only here if we refactor it. I can try doing it later.

Basically the idea is to change `CompositeConfigurationSource` to e.g. `Configuration`. It will not implement `IConfigurationSource` and existing code would depend on `Configuration` instead of `IConfigurationSource`. Then we will be sure that the "sanitization" is always applied.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1724#discussion_r1042457881_

**Comment by RassK** [comment]
This seems quite a big scope, since code is using composite source and tests are mainly using some specific source.
Transferring composite source to the tests makes the configuration layer quite fat for a single test + there is danger of leaking configurations (eg if env source is brought to the tests).
