### ISSUE TITLE
Error with AdditionalDeps on macOS

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2036]
Full interaction at https://cloud-native.slack.com/archives/C01NR1YLSE7/p1674162631314489

Instrumentation caused a crash on the app even after some workarounds were applied to the instructions for macos. The error message was 
```
An assembly specified in the application dependencies manifest (Openelemetry.AutoInstrumentation.AdditionalDeps.deps.json) was not found: package: 'DnsClient', version: '1.4.0' path: 'lib/netstandard2.1/DnsClient.dil'
```
There were no logs on the user's machine. Initially, I wasn't able to repro the same on a macos, which indicates that something is still wrong with the user config. However, it is not clear what is broken with the config.

**Comment by rajkumar-rangaraj** [comment]
Error message indicates it is not able to locate the runtime store. Here are few things we could ask customer to verify.

- Check `DOTNET_SHARED_STORE` is pointing to a valid location
- Validate there are contents in runtime store folder
- While decompress a zip file, it might have not copied files from `store` due to long path

**Comment by ramanjaneyagupta** [comment]
DOTNET_SHARED_STORE is pointing to a valid location
And seeing contents in store folder
Tried installing multiple times but still seeing the same issue
Also tried installing latest dotnet version that is 7.0.102

**Comment by pellared** [comment]
Can you share a minimal working example so that we can reproduce the issue? I think sharing the code which you want to instrument (I suggest cutting down the code to minimum) and shell (and which shell) commands that you execute. 

The problem is that for our examples everything seems to work. All our integration tests are passing on macOS and the smoke test is passing as well. https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3994013767/jobs/6851250881

**Comment by pellared** [comment]
1. Are you using `sh` (or `bash`) instead of `zsh`?
2. If I remember correctly in `sh` you must use `.` instead of `source`. Therefore you should execute: `. $HOME/.otel-dotnet-auto/instrument.sh`

Let me know if it helps. If it won't help I will do my best to dedicate some time this week and take a deeper look.

**Comment by ramanjaneyagupta** [comment]
@pellared tried with sh and bash and resulting the same

**Comment by RassK** [comment]
`Mine is Apple M1 not sure it may differ execution environment, but after installing and running`

Apple M1 won't be compatible, related issue https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1865

**Comment by pjanotti** [comment]
[Source instrumentations](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/design.md#library-instrumentations) are supported on Apple M1, but, need the temporary workaround in #2181 

I'm closing this issue since we should have covered and understood all the issues here.
