### ISSUE TITLE
log issues in auto instrumentation

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#2183]
# Bug Report

3 issues about log in auto instrumentation:
- debug is always on
  ideally, it is configurable to switch on/off of debug level in logging.
- logging is stopped after log file size reached 10 MB
  we probably need a rotation mechanism so that logging can continue after reaching a file size limit.
- log file clean up
  there will be a lot of log files after applications keep running for a long time. we probably need a clean up mechanism based on retention policies.

**Comment by pellared** [comment]
Related issues:

- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/372
- https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/469

**Comment by pjanotti** [comment]
Adding support to disable logging via something like #372 seems a good idea. That said there are a few issues opened related to our logging. It seems a good opportunity to define a small plan instead of taking incremental changes. The top Q that we have to decide is if we should adopt the same mechanism as the SDK? If yes, what about native .NET Framework logging?

**Comment by Kielek** [comment]
First post 0.6.0 version should contains all changed.

**Comment by lachmatt** [comment]
All of the requirements should be met:
- logLevel is configurable using `OTEL_LOG_LEVEL`
- rotation mechanism is in place
- max 10 log files should be retained
