### ISSUE TITLE
Bootstrap OpenTelemetry SDK Using Dotnet Startup Hook

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#225]
<H3>.NET Core Startup Hook Proposal</H3>

.NET Core 3+ and .NET 5+ provides a low-level hook that allows injecting managed code to run before the main application's entry point. Take advantage of dotnet startup hook to bootstrap OpenTelemetry SDK to an application.

Currently, OpenTelemetry Dotnet Instrumentation has a requirement to include System.Diagnostics.DiagnosticSource, or other instrumentation package reference at build time to instrument an application with OpenTelemetry SDK. Proposal here is to use dotnet startup hook to load OpenTelemetry SDK dynamically into an application without taking package references. 

```text
+-------------------+      DOTNET STARTUP HOOK     +-------------------------+
|    Application    |   <-----------------------   |    OpenTelemetry SDK    |
+-------------------+                              +-------------------------+
```
<H3>Advantages</H3>

- **Zero-Touch Enablement**: Set `DOTNET_STARTUP_HOOKS` environment variable value to the location of startup hook assembly to inject OpenTelemetry SDK to an application
- **Better performance**: Low performance cost for an application that does not require byte-code instrumentation
- **Low maintenance**: This helps always point to the latest version of instrumentation library. Customer don't need to worry about updating Nuget package reference in their app

<H3>Limitation</H3>

- If the application has a reference to lower version of `System.Diagnostics.DiagnosticSource` than the one referenced in OpenTelemetry SDK. This approach may not work. Workaround is to refer to the same `System.Diagnostics.DiagnosticSource` in package reference as of OpenTelemetry. This limitation could be overcome by creating a proxy or adaptor to convert the `Activity` created in lower version to OpenTelemetry version. Will propose this in a new issue.  

<H3>Reference</H3>

[Dotnet Host Startup Hook](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md)

**Comment by pellared** [comment]
I think that this issue can be split into a few phases. 

The first is to create an assembly that can be used in `DOTNET_STARTUP_HOOKS`. 

Next would be to refactor the codebase to strip down this assembly so that it references only the necessary code (e.g. it does not reference all code connected with the Profiler).

At last, we could introduce the mechanism allowing different versions of `System.Diagnostics.DiagnosticSource`. It would be good if the mechanism would work for both the .NET Startup Hook and for the .NET Profiler setup.

All of these should be done on top of the `poc-otel-sdk`  branch _which hopefully would become the `main` branch soon_.

Does it seem reasonable?
