### ISSUE TITLE
Inconsistency between native and managed code handling of OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#2441]
Most of the time the inconsistency shouldn't be a problem, but, for `dotnet` CLI it can be noticeable:

- The native code uses the process module name
- The managed code uses the `AppDomain.CurrentDomain.FriendlyName`

**Comment by nrcventura** [comment]
Here is a little more information about the reason for the difference in behavior. 

When we first started to use the StartupHook to load the managed code, the StartupHook attempted to load the auto instrumentation into the dotnet process (for certain ways of starting the application). In that situation, we needed to determine if the current process was actually `dotnet` or if it was the application that should be instrumented. The Process itself didn't provide enough information to differentiate the applications, because I remember seeing that the process name could sometimes be the same name `dotnet`. In that situation when the process names were both `dotnet` they would have different AppDomain names. So that is the reason for the divergence in this behavior.

I'm leaning towards using a separate environment variable for the startup hook and renaming the current environment variables. I think that having a separate environment variable can lead to less confusion, and if we rename them to clarify that one applies to the profiler and the other applies to the startup hook, that can also help with the confusion. In the past we had an issue because the managed code did not support the `OTEL_DOTNET_AUTO_INCLUDE_PROCESSES` environment variable. If the managed code used a different environment variable, there might be less of an expectation to support the include/exclude symmetry on the managed side.

**Comment by RassK** [comment]
My best idea currently:

- No modifications to native behaviour of `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES`
- Modify `ApplicationInExcludeListRule` with:
   * `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` => `Process.GetCurrentProcess().ProcessName`
   * `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` => `AppDomain.CurrentDomain.FriendlyName`
   * Document `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` only for StartupHook

**Comment by nrcventura** [comment]
> My best idea currently:
> 
> * No modifications to native behaviour of `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES`
> * Modify `ApplicationInExcludeListRule` with:
>   
>   * `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` => `Process.GetCurrentProcess().ProcessName`
>   * `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` => `AppDomain.CurrentDomain.FriendlyName`
>   * Document `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` only for StartupHook

I think that will work, but we also will need to ensure that we update any installation scripts and default values to ensure that `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` is set correctly.

**Comment by RassK** [comment]
Can't remember that our setup scripts actually address the possibility to run without native part. I guess it's for advanced users only, when doing manual setup.

**Comment by pjanotti** [comment]
I'm having second thoughts and going in the direction of only making them consistent. Basically:

> My best idea currently:
> 
> * No modifications to native behavior of `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES`
> * Modify `ApplicationInExcludeListRule` with:
>   
>   * `OTEL_DOTNET_AUTO_EXCLUDE_PROCESSES` => `Process.GetCurrentProcess().ProcessName`
>   * ~~`OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` => `AppDomain.CurrentDomain.FriendlyName`~~
>   * ~~Document `OTEL_DOTNET_AUTO_EXCLUDE_APPDOMAIN` only for StartupHook~~


* Typically we don't enable auto-instrumentation machine-wide, so in the default case, the user doesn't need to deal with these environment variables - it is an advanced configuration. The recommended path is to use the setup script and use a script to set the env vars on the appropriate scope.
* The case to use this configuration is when the installation is done machine-wide. In this case, it makes sense to exclude processes like `powershell`, `pwsh`, and perhaps `dotnet`. The only problematic case in this context is if the user wants to instrument an app and launch it with `dotnet <app.dll>`.  However, this case can be handled by instead launching the process with the `<app_executable>` directly or alternatively by removing `dotnet` from the excluded processes just for the launch of `dotnet <app.dll>`.
