### ISSUE TITLE
Azure SDK tracing - support on .NET Framework

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2796]
Partially revert changes from #2795.

Ensure that it pass on Windows with Docker for linux on .NET Framework

**Comment by rajkumar-rangaraj** [comment]
I've been testing Azure SDK tracing using a .NET Framework application. In addition to the standard auto-instrumentation configurations, I specifically enabled Azure SDK support by setting the `OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES` environment variable to `Azure.*` and the `AZURE_EXPERIMENTAL_ENABLE_ACTIVITY_SOURCE` to `True`. However, with these settings, I observed that no Spans (Activities) were collected from the Azure SDK.

Interestingly, when I set the `OTEL_DOTNET_AUTO_NETFX_REDIRECT_ENABLED` environment variable to `false`, the data collection issue was resolved, and I was able to gather data from the Azure SDK successfully. With redirection enabled, the diagnostic logs were stored under the file name `otel-dotnet-auto-native-TestApplication.Azure-32972`, and without redirection, the file name was `otel-dotnet-auto-TestApplication.Azure.exe-10692-20230815`.

We need to analyze the differences to determine what might be causing these redirection issues.

**Comment by pjanotti** [comment]
@rajkumar-rangaraj This seems similar to #2833: the test applications have explicit references to S.D.DS 7.0.0 and the Fx assembly redirection fails for that. It indeed ends with both versions loaded. When the automatic redirection is disabled version 7.0.0 is used the spans are captured.

In principle, we just need 7.0.2 for .NET Framework apps, however, for any .NET Framework app 7.0.2 is a must. In order to simplify things we likely should change the docs and tests all to 7.0.2.

**Comment by pjanotti** [comment]
There is still something missing in the picture above: I wasn't able to get both Azure and Http instrumentation to work on a .NET Framework application. Tweaking `AZURE_EXPERIMENTAL_ENABLE_ACTIVITY_SOURCE` and `OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES` one or the other, but, not both instrumentations at the same time (as for .NET 6.0 and 7.0).

**Comment by pjanotti** [comment]
The HTTP instrumentation _disappears_ when Azure instrumentation is enabled on the .NET Framework because the Azure instrumentation injects headers for context propagation and a check on the HTTP instrumentation explicitly skips instrumentation if the header is present, see 

- https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs#L279-L284 
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs#L262-L264
