### ISSUE TITLE
OpenTelemetry .NET Auto-Instrumentation not showing database queries

### ISSUE THREAD

**Issue by NamitaJaokar** [open-telemetry/opentelemetry-dotnet-instrumentation#305]
Hi,

I have configured OpenTemeletry .Net Auto instrumentation which is a pre-release version with a sample mvc application that uses postgresql database-(Npgsql.EntityFrameWorkCore.PostgreSQL) with EntityFrameworkCore instrumentation. The agent works with zipkin exporter and I am able to view the traces in the zipkin dashboard.
However, I want the database statements to be seen which currently cannot be found in the traces. Which environment variable do I need to set so as to get the database statements in the zipkin dashboard. In current configurations, I can only view db.name="dbname" , db.type="postgres", name="postgres.query" as database attributes.
The same application when manually instrumented with OpenTelemetry's AddEntityFrameworkCoreInstrumentation(options.setDbStatementForText=true) was able to give the desired result.

What configurations will be required to get the db.statement that will have the select/update/insert/ queries as the value.

Sample Trace:
![image](https://user-images.githubusercontent.com/32196871/148014386-ff04a27e-8afc-4d67-82e0-9de238de590a.png)

**Comment by pellared** [comment]
I quickly looked at [legacy-main](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/legacy-main) and I do not see anything that would populate `db.statement`.

Also per https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/226 we have taken a different approach so we are not supporting the mentioned pre-release.

**Comment by NamitaJaokar** [comment]
Hi @pellared , 

Thank you for providing required information. To add more on this, In the future release of the auto-instrumentation, Is there a way we can find the database queries if not in the db.statement. In the unsupported version's tracer logs , I was able to view the database queries in the Resources key of the traces.

Could you please guide me on this in any way.
Thanks in advance.

**Comment by nrcventura** [comment]
@NamitaJaokar we are not yet ready to expand the number of libraries that are instrumented by this project, and are working on improving the experience for a small subset of libraries so that we can start to get some usage feedback. However, when postgresql support is added (which I believe is important for us to support) we will follow the semantic conventions for database instrumentation which at this point in time [defines that the query should go in `db.statement`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes). I don't know why the query isn't getting captured in the code within legacy-main, but I am not aware of anything that would prevent us from capturing the query when we add support for postgresql.

**Comment by NamitaJaokar** [comment]
Thank you @nrcventura for the detailed information.

**Comment by nrcventura** [comment]
I am not comfortable with providing a timeline or guess yet, because we do not have our first prerelease published. With that being said, according to https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#open-telemetry-for-adonet-providers, there seem to be plans to have OTel instrumentation built into npgsql.
