### ISSUE TITLE
Build a NuGet package that adjusts all of the dependency references

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#316]
Build an nuget package that adjusts all of the dependency references so that it can be used to mitigate the issue when the application uses a different version of OTel .NET SDK,  `System.Diagnostics.DiagnosticSource` or any other dependency that can cause problems.

_Originally posted by @RassK in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/307#issuecomment-1012176089_

**Comment by rajkumar-rangaraj** [comment]
If application has higher version of OpenTelemetry SDK than the Auto-Instrumentation OpenTelemetry SDK. Higher version wins and if there are breaking changes between these versions, auto-instrumentation might affect an application. We might need to consider using this option with caution.

**Comment by nrcventura** [comment]
Maybe instead of a nuget package to update the dependencies, would it be possible to have a nuget package that contains the auto instrumentation bits and updates the dependencies to match those bits so that everything will be consistent?

**Comment by pellared** [comment]
My biggest worry about creating a NuGet package is that as the number of  "source instrumentation" grows the more dependencies we will bring and it may lead to dependency hell.

However, I still think it is worth giving a try.

**Comment by rajkumar-rangaraj** [comment]
We might need to prioritize this issue. In the cases where `FileLoadException` are thrown like #1027 we could ask to refer the auto-instrumentation Nuget instead of those specific Nuget that is causing a failure. This would be a simpler workaround for many of these file load issues.

**Comment by nrcventura** [comment]
I like the idea of having a Nuget package to help with those dependencies, however I think that deciding what should go in it is a little less straightforward and will probably not handle all of the current `FileLoadException` issues. For example, the [missing AspNetCore.Features library](#975) should probably not be in that Nuget package, so the Nuget package will not help resolve that specific issue. I also think that the [unsafe compiler services dependency](#1076) should be handled differently, so the Nuget issue would only help until we fix that direct dependency. As a result, I think we should have a better idea about which specific problems this type of Nuget package could help with resolving in order to determine if it is worth the maintenance cost.
