### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3168]
>Same issue here. Where the project, or dependant projects, have direct dependencies on Microsoft.Extensions.* 6.0, we are having `Could not load file or assembly` issues. Adding OpenTelemetry.AutoInstrumentation nuget package does not solve the issue.
> 
> I am not familiar on how the injection mechanism work, but why a net6 project should hard reference Microsoft.Extensions 7.* packages?
Shouldn't be that depending on the target framework, the dependancy is >= [targetframework].*

_Originally posted by @federicobarera in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3075#issuecomment-1832168095_

**Comment by Kielek** [comment]
@federicobarera, could you please create [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? It should include all steps you are using to build the package.

**Comment by federicobarera** [comment]
Hi, you can find a repro with instructions here: https://github.com/federicobarera/otel-auto-repro

**Comment by rajkumar-rangaraj** [comment]
To resolve an issue, you have to either remove this package reference or update it to version 7.0.0: `<PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />` in the https://github.com/federicobarera/otel-auto-repro/blob/master/Dependencies/Dependencies.csproj. We are aware of the root cause of the issue and will address the application crash issue in the next version. Instead of crashing the app, it should safely back off and provide more detailed information in the log files to aid in fixing the issue.

**Comment by federicobarera** [comment]
@rajkumar-rangaraj, @Kielek 

I have a couple more questions regarding this issue.

I did read the [Troubleshooting](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#assembly-version-conflicts) and we eventually managed to align the dependencies in the test project, however it is stated on the docs that adding OpenTelemetry.AutoInstrumentation should have automatically sorted the dependencies. Given we are planning a fairly large rollout, across tens of teams and projects, we hoped for the autoinstrumention not to require code changes. Is there any plan for auto the auto instrumentation libraries to work with available libraries instead of forcing the requirement on 7.x

net8. We also had problem with net8 and the 0.43 operator (referencing 1.11 tag - Microsoft.Extensions 7.x).
Given the next verson 1.12 is referencing 8.x is it expected for all applications (net6 and 8) to take dependency on Microsoft.Ex 8.x?

**Comment by rajkumar-rangaraj** [comment]
@federicobarera OpenTelemetry .NET SDK has reference to old version of `Microsoft.Extensions.Logging.Configuration`. Hence the usage of NuGet did not help.

      "OpenTelemetry/1.6.0": {
        "dependencies": {
          "Microsoft.Extensions.Logging.Configuration": "3.1.0",
          "OpenTelemetry.Api.ProviderBuilderExtensions": "1.6.0"
        },
        "runtime": {
          "lib/net6.0/OpenTelemetry.dll": {
            "assemblyVersion": "1.0.0.0",
            "fileVersion": "1.6.0.1006"
          }
        }
      },

Next Version (1.7) version of OpenTelemetry .NET SDK has 8.0.0. version of `Microsoft.Extensions.Logging.Configuration`. When auto-instrumentation takes reference to next version of OpenTelemetry .NET SDK, this issue will be resolved.  OpenTelemetry .NET SDK might release 1.7 version of SDK next month.
