### ISSUE TITLE
The AppDomain.CurrentDomain.UnhandledException += OnUnhandledException not shows the Stats data in the end

### ISSUE THREAD

**Issue by lipingma** [open-telemetry/opentelemetry-dotnet-instrumentation#3742]
# Bug Report

## Symptom

**Describe the bug**
When the code runs to OnUnhandledException in Instrumentation, it not shows the Stats data in the end.

For process exit, it will show the Stats data in the end like: 
[info] Stats: Total time: 8810ms | Total time in Callbacks: 68ms [Initialize=3ms, ModuleLoadFinished=28ms/10, CallTargetRequestRejit=4ms/13, CallTargetRewriter=0ms/0....

**Expected behavior**
Is this expected not showing Stats data when there is unhandled exception?

**Screenshots**

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0]
- OS: [e.g. Windows Server 2012 R2 ]
- .NET version: [e.g. .NET Framework 4.6.2, .NET Core 2.1]

**Additional context**

## Reproduce

 1. First step;
 2. Second step;
 3. etc

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>

**Comment by nrcventura** [comment]
I do not understand the problem that you are describing in this issue, other than the output in the application stops when an unhandled exception occurs (which causes the process to terminate). Can you tell us more about the application, the configuration that you are using, etc.? Ideally, please provide a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem.

**Comment by RassK** [comment]
I guess the context here is about console app?

ASP.NET Core app does not shutdown the runtime in case of unhandled exception. When you exit the process gracefully shutdown stats are still printed.

Unhandled exception in console app does terminate the program so that .NET native profiler does not execute shutdown. If you want to exit gracefully do use `Environment.Exit(1);` in `AppDomain.CurrentDomain.UnhandledException` and shutdown stats are printed.
