### ISSUE TITLE
Change naming for Samples and Examples application

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#484]
In this repo Sample application means application used in tests. Example application is app just to illustrate something, placed in different folder.

I hope you find a way to rephrase to differentiate the usage. Alternatively, we can try to change the code if you have better names :)

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/483#discussion_r848395578_

Based on conversation with @theletterf,
We should change
Sample.* applications to TestApplication.* and all Example.* applications to Sample.*.

**Comment by pjanotti** [comment]
> Sample.* applications to TestApplication.* 

I agree, perhaps keeping the plural

> Example.* applications to Sample.*.

That I'm not so sure. Any particular reason for that? I like "Example" in this case because we are not sampling and it is consistent with the SDK.

**Comment by theletterf** [comment]
@pjanotti The problem with "Example <sth>" is that "Example" cannot be used as an adjective—"Sample" can. So it should either be "Sample <sth>" or "<sth> example" (compound noun).

**Comment by pjanotti** [comment]
Re-opening the issue so we use to settle the question about "sample" vs "example".

**Comment by theletterf** [comment]
So, we use "example application" or "example code" in the docs, and that's not correct, because "example" cannot be used as an adjective. We could just say "example" or "application example", or switch to "sample". In my opinion, we can do this in the docs while keeping the code intact.

Edit: I see now that some docs (for example, AWS) use "example application" as a compound noun, so I guess we can keep that in the code as it is. (Sorry, typical tech writing rambling.) :-) 

My suggestion: let's not change Example.* applications to Sample.*. in the code, but keep that flexible in the docs unless it could be heavily confusing to maintainers. In that case, I'd revert the changes in the docs (which is tolerable).

**Comment by Kielek** [comment]
@theletterf, `Sample.` is no longer keyword so it is pretty obvious that it refers to Example apps.
Note from last SIG meeting. The 'sample' is heavily used in context of 'sampling'.  It can be confusing for our users.

**Comment by theletterf** [comment]
@Kielek I've reverted the language in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/483/commits/65c82848c42bba6edc966013d7ec70f7757c0deb — have a look.

**Comment by Kielek** [comment]
@theletterf, I know that you are not happy from such solution, but I think that for now, we can keep it as it is. Thank you!

**Comment by theletterf** [comment]
@Kielek Oh it's OK. :) One must be flexible!
