### ISSUE TITLE
[Redesign idea] Remove OTel .NET SDK related code, only do byte-code instrumentation to emit activities

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#571]
## Idea

Reduce the scope of OTel .NET AutoInstrumention to only add byte-code instrumentation using .NET Profiler.

## How 

Remove the dependency on `System.Diagnostics.DiagnosticSource` and OTel. NET SDK. Use reflection (or "Duck typing") in places like: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/04dbda40cb418a13d2ee69be1ea442b192b54294/src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs#L43-L44

The application is responsible for bootstrapping the OTel .NET tracer.

## Benefits

The bootstrapping would be exactly the same as when using https://github.com/open-telemetry/opentelemetry-dotnet . This project would simply instrument libraries that do not use `ActivitySource` to emit traces. This should remove the problems connected with dependency conflicts. It should also increase the maintainability of this project (fewer problems to deal with).

## Drawbacks

Requires access to code access to do setup ANY instrumentation in order to bootstrap the tracer, exporters, etc. Not possible to instrument 3rd party .NET applications without IL recompilation.

## Sidenote

I guess we need feedback from beta before we make any decision. Right now I want to at least know if this could be technically working and if it could be acceptable.

**Comment by nrcventura** [comment]
Just some early thoughts...

There are concepts mentioned here that I think can mostly be treated separately:

1. Auto-configuration/bootstrapping - loading of dependencies and configuration of the SDK
2. Byte-code instrumentation

Without supporting some amount of auto-configuration/bootstrapping we will be unable to support the devops scenarios (enabling the collection of telemetry data without requiring a rebuild of the application). 

Supporting byte-code instrumentation can be handled independently of the devops scenario. We still need to validate if we can leverage something [DiagnosticsClient api](https://github.com/dotnet/diagnostics/blob/73220eed795c37dff1bf8553bc206db3e0585138/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs#L192) to simplify the setup of enabling a profiler, but otherwise I think we could have a nuget package (or multiple packages) plus some manual configuration of environment variables (to enable the profiler) to handle that simplified use case. 

At this point in time, the .NET ecosystem has many available source-based instrumentation libraries available, and the need for byte-code instrumentation is getting smaller. As a result, I think that it's important for us to focus on the devops scenario, and improving the bootstrapping process.

We may decide, based on feedback, that we should offer a nuget package so that byte-code instrumentation can be directly used by the OTel SDK. I just don't think that we need to maintain that complexity yet.

It may also be a good idea to take an approach somewhere between the one in this issue, and the full devops support. We could have a nuget package that handles dependency management at build time. It would not install this project, it's just a way to get the dependencies to line up correctly, so that things can safely be loaded at runtime dynamically.
