### ISSUE TITLE
Help Getting Started - how to instrument an ASP.NET application deployed on IIS

### ISSUE THREAD

**Issue by ZZBrent** [open-telemetry/opentelemetry-dotnet-instrumentation#631]
I recently discovered this repo and was excited to see that there was a .NET Auto Instrumenter in Beta for Open Telemetry.  I quickly got approval to deploy it onto a test server.  However, now that I have, I am not sure if it is working correctly.  I will lay out all of the steps I went through below.  I feel like I am missing something simple, but the "Get Started" section of the read me only had 2 steps, so I am not sure what else to try or look at:

1. Downloaded the [Beta Release](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.1.0-beta.1) files and unzipped them onto my Windows Server 2016 machine into the C:\.NET Profiler folder.
2. Opened the "Edit the system environment variables" window, clicked the "Environment Variables.." button, and created all of the environment variables mentioned in the Get Started section of the readme file:
COR_ENABLE_PROFILING=1
COR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
COR_PROFILER_PATH_64=C:/.NET Profiler/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll
COR_PROFILER_PATH_32=C:/.NET Profiler/win-x86/OpenTelemetry.AutoInstrumentation.Native.dll
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
CORECLR_PROFILER_PATH_64=C:/.NET Profiler/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll
CORECLR_PROFILER_PATH_32=C:/.NET Profiler/win-x86/OpenTelemetry.AutoInstrumentation.Native.dll
DOTNET_ADDITIONAL_DEPS=C:/.NET Profiler/AdditionalDeps
DOTNET_SHARED_STORE=C:/.NET Profiler/store
DOTNET_STARTUP_HOOKS=C:/.NET Profiler/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll
OTEL_DOTNET_AUTO_HOME=C:/.NET Profiler
OTEL_DOTNET_AUTO_INTEGRATIONS_FILE=C:/.NET Profiler/integrations.json
3. Opened IIS:
    a. Changed my two .NET 5 applications (which are set up as APIs) to use .NET CLR 4.0.30319 (there were using no managed code previously, but from my understanding, it needs to be managed to work with a .NET profiler so that the code can be modified).
    b. Restarted the app pool for the two applications
4. Used Postman to send a successful request to one of the applications
5. Looked in %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs and the current user's temp folder for logs, but did not see any logs or files listed in either location

If I missed any steps in this process, or am doing anything wrong with this setup, please let me know.  My goal here is to not only get my server running with the .NET Auto Instrumentation, but also to provide more thorough instructions to anyone else wanting to set this up for the first time.

Thank you for any advice and/or troubleshooting tips you can provide regarding this.

**Comment by Kielek** [comment]
@ZZBrent, did you changed the `%InstallationLocation%` to your real path (`C:/.NET Profiler`)? 

If you do not see any logs, OTel AutoInstrumentation is probably not started.

**Comment by ZZBrent** [comment]
> @ZZBrent, did you changed the `%InstallationLocation%` to your real path (`C:/.NET Profiler`)?
> 
> If you do not see any logs, OTel AutoInstrumentation is probably not started.

Thank you for the immediate reply.

Yes, in the environment variables, I did change the `%InstallationLocation%`.  I have edited the above to reflect that.

Is there anywhere else I can check to see if it is running?  Is there anything I need to do initially to run it?

**Comment by nrcventura** [comment]
IIS hosted applications, and aspnetcore applications hosted in IIS using the aspnetcore module, get their environment variables differently than other applications (usually the system registry or a config file). They may not pick up the system environment variables until after a system restart.

You are correct that this project can only instrument or load instrumentation for managed code.

Which libraries are your .NET applications using? If your applications are each using different libraries you will likely need to specify some application specific environment variables. The `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` environment variable controls which instrumentation libraries will be used. To see which libraries are supported refer to our [full list of instrumentation libraries](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#instrumented-libraries-and-frameworks).

There are other settings that should consider, which include [how you want the telemetry data exported](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#exporters), and [identifying information for your application](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#resources).

**Comment by pellared** [comment]
As far as I remember you probably need to restart W3SVC and/or WAS Windows Services.

If you do not want to set system environment variables you can set it via, you can set the `Environment` registry key for W3SVC and WAS services located in the` HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` folder.

Also for ASP.NET Core applications it should be possible to set [environmentVariable](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config#set-environment-variables) elements inside the `<aspNetCore>` block of your `web.config` file.

**Comment by ZZBrent** [comment]
I was able to set the environment variables within the web.config file and that is now creating records in the expected folder.

Now, from my understanding, these records should contain the logs from my applications.  However, I am not actually seeing any details about the app or the codebase, rather just information about the profiler itself.  For example, if I make an API call to the application, the logs definitely update when it happens, but there does not appear to be any data or information in the log file related to the API call or what actually happened when it was made (just a log saying that the profiler is attached and another log saying that tracing started and completed successful).  Do I need to enable a configuration value to create deeper logs at the code level (saying which functions or calls were made) or does that need to be done manually at the code level?

From my understanding of the docs, tracing requires an exporter to be setup using the OTEL_TRACES_EXPORTER and OTEL_EXPORTER_OTLP_ENDPOINT environment variables.  For that step, I attempted to add my New Relic instance.  However, in other OpenTelemetry documentation I am seeing an environment variable for headers, where I am supposed to put in my unique API key for New Relic so that New Relic knows the data I am sending is connected to my account.  Is there an environment variable for this project that corresponds to that header values (or a separate one for API keys)?

Again, thank you for any assistance you can give regarding this project!  I hope these questions will help give some feedback regarding the Beta and I am happy to help put together some documentation about my full experience of getting this set up through IIS to avoid others having these issues/questions in the future.

**Comment by nrcventura** [comment]
@ZZBrent Thank you for updating us on your progress! I recently put together [an example](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/dotnet/agent-nr-config) on how to use this project and configure it to send data to New Relic. The example uses docker just so that I could more easily demonstrate how to download, install, configure, and run things without creating a bunch of shell scripts and OS specific things.

You are correct that there are some additional environment variables to specify (including one to add your license key/api key to the OTLP headers). You can find information about them in a few locations: 

- The [example README](https://github.com/newrelic/newrelic-opentelemetry-examples/blob/main/dotnet/agent-nr-config/README.md#run)
- Comments in the environment variable section of the [example Dockerfile](https://github.com/newrelic/newrelic-opentelemetry-examples/blob/c4c77ba4e350275368047b081db16b77eb8d6610/dotnet/agent-nr-config/Dockerfile#L33-L39)
- New Relic's OpenTelemetry [getting started information](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/). The header environment variable is not directly documented on that page, because it delegates that documentation out to the OTel docs for the specific languages. It does however contain some useful information about the New Relic endpoints and ports.

Another environment variable that you'll want to set appropriately for your application is the `OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS` that I mentioned in a [previous comment](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/631#issuecomment-1111247120).

The logs that this project generates does not contain your telemetry data, but they can contain information about errors that were encountered when trying to observe and transmit the telemetry data for your application. This project does not yet support collecting application log data, but if things are working as expected, it should collect trace data (spans/activities) but we do not store that information in the log files that we generate.

Please continue to reach out and let us know how things are progressing, and feel free to provide some feedback. Positive and constructive feedback are both greatly appreciated.
