### ISSUE TITLE
Review markdown lint settings

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#638]
See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/635#discussion_r861158800

**Comment by Kielek** [comment]
@pjanotti , we are referencing https://keepachangelog.com/en/1.0.0/.
It suggests strict headers for the changes 

```
Added for new features.
Changed for changes in existing functionality.
Deprecated for soon-to-be removed features.
Removed for now removed features.
Fixed for any bug fixes.
Security in case of vulnerabilities.
```

By default MD024 does not allow to have more than one header with the same name. It is impossible to make unique link to the header `https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/CHANGELOG.md#added` links to Unreleased -> Added and 0.1.0-beta.1 -> Added.

With current configuration we allow this duplicated headers. I think that it is fine, as we more likely link to exact version header instead of exact _Added_ header.

**Comment by pellared** [comment]
We can disable `MD024` by adding `<!-- markdownlint-disable-file MD024 -->`  in `CHANGELOG.md` (it can be placed even on the bottom of the file) instead of disabling it globally. WDYT?

**Comment by RassK** [comment]
> We can disable `MD024` by adding `<!-- markdownlint-disable-file MD024 -->` in `CHANGELOG.md` (it can be placed even on the bottom of the file) instead of disabling it globally. WDYT?
> 
> Reference: https://github.com/DavidAnson/markdownlint#configuration

I was considering it also. I think currently the global rule is restrictive enough (not to cause duplicates in sibling level) and in same time free enough for different heading trees.

**Comment by pellared** [comment]
@pjanotti WDYT?

**Comment by pjanotti** [comment]
SIG meeting: closing issue, rule was very specific.
