### ISSUE TITLE
Potential data loss

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#976]
@Kielek I'm worried this is a design flaw. If we wait for all of these threads to exit and then do our graceful shutdown, there is going to be data loss.

_Originally posted by @CodeBlanch in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/528#issuecomment-1192840018_

**Comment by Kielek** [comment]
@CodeBlanch, could you please explain your concerns for all @open-telemetry/dotnet-approvers?

**Comment by nrcventura** [comment]
I'm interested in hearing more about the issue, but my best guess about the concern that was brought up, is that once the OnExit event is fired, there may not be enough time for all of these threads to complete, and that they complete in the right order, so that all of the data can be sent successfully.

When things are going well, and the destination(s) for the data are available and there are no networking delays or errors, there is usually enough time to flush all of the data. I have mostly seen problems with flush data OnExit approaches when there is some sort of error. Those scenarios usually involved something like some sort of networking delay or error that triggered a timeout, some sort of protocol violation (which might be vendor or protocol specific), or even back pressure that might trigger a later retry. 

Whether or not the thread is a foreground or background thread, we still have the risk of potential data loss. I don't think that the background thread in the instrumentation library significantly increases that risk. OnExit should only occur when the application is done handling requests or processing data. It is possible that there is background work in the application that is interacting with Redis that is still running while the application is exiting, but under normal circumstances, a typical application would wait to complete those background jobs before the OnExit event is triggered, otherwise the application itself runs the risk of losing data.

**Comment by CodeBlanch** [comment]
@Kielek Hey I just whipped up a quick test application and took it for a spin. I don't think there is an issue. Sorry I was misunderstanding how it was working. What I thought was happening was the background threads would spin down and then the exit logic would fire. That would lead to data loss. But what is actually happening is the threads are still alive when the logic fires.

@nrcventura raises valid points but as far as my concerns, I think we're good 👍

**Comment by pellared** [comment]
@CodeBlanch Thanks for your feedback and there is nothing you should be sorry about 👍
